apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
  namespace: default
data:
  app.properties: |
    key1=value1
    key2=value2
  environment: production

---
apiVersion: v1
kind: Secret
metadata:
  name: demo-secret
  namespace: default
type: Opaque
data:
  username: dXNlcm5hbWU=  # base64 encoded "username"
  password: cGFzc3dvcmQ=  # base64 encoded "password"

---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  namespace: default
spec:
  containers:
    - name: demo-container
      image: nginx
      env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: demo-config
              key: environment
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: demo-secret
              key: username
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        - name: secret-volume
          mountPath: /etc/secret
  volumes:
    - name: config-volume
      configMap:
        name: demo-config
    - name: secret-volume
      secret:
        secretName: demo-secret
